### ISSUE TITLE
sphinx.ext.pngmath docs error

### ISSUE THREAD

**Issue by jsta** [uwescience/shablona#30]
When I run `make html` in the `doc` directory I get the following error:

> Config value 'math_number_all' already present

Commenting out line 62 reading `sphinx.ext.pngmath,` following https://github.com/NYUCCL/psiTurk/commit/e31484e71fbf64dee1760e6dd3095f7e1ed24fc6 appears to fix the issue.

**Comment by arokem** [comment]
Just to understand: you are getting this error in the shablona documentation, or have you added anything to the documentation above and beyond what's in the shablona repo? I am not seeing this error, so I would like to first understand under what circumstances you might see this. Also, Python version, OS, sphinx version? Anything else that might be pertinent?

**Comment by jsta** [comment]
I have not added anything beyond the shablona repo. Simply `git clone`, `cd doc`, `make html`.

Python version: 3.5.1
OS: Ubuntu 16.04
sphinx: 1.4.1

**Comment by arokem** [comment]
Interesting. Even after updating to sphinx 1.4 (I was previously on sphinx
1.3) I still don't get this error. Unfortunately, sphinx is one of the
hardest things to debug. Let me see if we can just happily live without
that extension altogether. Maybe we don't even need it...

Thanks for reporting this!

**Comment by arokem** [comment]
FWIW, it seems that pngmath is deprecated: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/pngmath.py#L6

If you replace that line with `sphinx.ext.imgmath`, does it work for you?

**Comment by arokem** [comment]
For me sphinx doesn't seem to be able to find the new extension at all.

**Comment by jsta** [comment]
Replacing that line with `sphinx.ext.imgmath` does not work for me. I did a fresh pull and the only way I could get the docs to build was commenting-out/removing that line.

**Comment by jsta** [comment]
This no longer seems to be an issue.
