### ISSUE TITLE
Don't recommend travis cacheing for conda

### ISSUE THREAD

**Issue by jakevdp** [uwescience/shablona#50]
I know I initially added Travis cacheing, but after a few negative experiences I'd now recommend against it. Basic rationale:

1. a script that fails on a clean environment might succeed when parts of an old environment are cached
2. in most cases, retrieving a cached environment takes about as long as creating that environment from scratch, so there's very little benefit.

I'm happy to do a quick PR removing the cacheing if people agree.

**Comment by arokem** [comment]
+1 from me

**Comment by arokem** [comment]
Fixed through #51
