### ISSUE TITLE
Why not fork and clone?

### ISSUE THREAD

**Issue by mbeyeler** [uwescience/shablona#65]
I am confused about the following bit in the instructions:

> To use this repository as a template, start by cloning it to your own computer under the name you will want your project to have:
> 
> ```
> git clone https://github.com/uwescience/shablona smallish
> cd smallish
> ```
> To point to your own repository on github you will have to issue something like the following:
> 
> ```
> git remote rm origin
> git remote add origin https://github.com/arokem/smallish
> ```
> (replace arokem with your own Github user name).

Why not just fork and clone? It seems that's what you are trying to achieve anyway by removing `origin` and adding a new remote.

**Comment by arokem** [comment]
You can only fork a repository once, and Github will retain the forking relationship with that repo, unless you write them and ask them to disconnect this relationship.

That said, this is indeed clunky, and what we should actually do here is explain how to use the Github importer: https://github.com/new/import

**Comment by arokem** [comment]
Addressed in #68
