### ISSUE TITLE
Feature Request: setuptools

### ISSUE THREAD

**Issue by par2** [uwescience/shablona#7]
Is there reason for your choice of `distutils` rather than `setuptools`?  I've found the `setuptools` is needed in  creating the newer wheels using the `pip setup.py bdist_wheel` command.  Granted pip standarization is currently in a state of flux, perhaps the following is a better abstract and flexible standard for importing `setup`:

```
try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup
```

[1] Beazley, D. Python Essential Reference. 4th ed. Upper Saddle River: Addison-Wesley, 2009. p.154
[2] https://stackoverflow.com/questions/25337706/setuptools-vs-distutils-why-is-distutils-still-a-thing

**Comment by arokem** [comment]
We are now using setuptools (I am not sure when that changed...). Closing.
