### ISSUE TITLE
make as template repository

### ISSUE THREAD

**Issue by TejasAvinashShetty** [uwescience/shablona#80]
Just as a feature  request could we make this as a [template repository](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/)  this could be an alternative solution to #68 #65

**Comment by arokem** [comment]
This is great! Thanks for bringing this to my attention. I just checked the box for this in the settings and confirmed that there is a "use this template" button on the front page. I wonder whether this will resolve the authorship issues that stem from using shablona in projects.

**Comment by TejasAvinashShetty** [comment]
You are welcome @arokem Thanks for the prompt reply.
